# Generated by Django 3.2.7 on 2021-09-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('user_id', models.CharField(max_length=100, verbose_name='User ID')),
                ('access_type', models.CharField(max_length=50, verbose_name='Access Type')),
                ('api_url', models.CharField(max_length=50, verbose_name='Url Information')),
                ('api_options', models.TextField(max_length=1500, verbose_name='API Options')),
            ],
            options={
                'verbose_name': 'AuditLog',
                'verbose_name_plural': 'AuditLogs',
                'ordering': ['id'],
            },
        ),
    ]
